services:
  dev-postgres:
    image: postgres:15.4-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    networks:
      - bot-or-not
networks:
  bot-or-not:
    driver: bridge

