services:
  dev-postgres:
    image: postgres:15.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    networks:
      - bot-or-not
networks:
  bot-or-not:
    driver: bridge

